baseurl = "https://bwsi-remote-sensing-2020.github.io/remote-sensing-homepage"
title = "root@bwsi-remote-sensing"
theme = "hugo-theme-console"
languageCode = "en-us"
publishDir = "docs"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "links/"
  url = "links/"
  
  [[params.navlinks]]
  name = "photos/"
  url = "photos/"
